### ISSUE TITLE
Subsequent passed checks do not update PR status

### ISSUE THREAD

**Issue by krishna-acondy** [MorrisonCole/pr-lint-action#5]
Hello @MorrisonCole,

First off, many thanks for creating and publishing this Action. We've been using it on our private repos and find it super useful! 🙌 

I did find a small issue though, and it has to do with PR statuses.
When my PR lint check fails and I update the title of my PR, a subsequent passing check doesn't set the PR status to 'All checks passed'. You can also see this in the screenshot below from your example PR.

Normally, we don't merge a PR unless all checks have passed, and this is showing up some 'false failures'(when subsequent checks have passed).

I did have a look at the source code for the action, and it seems to me that maybe explicitly setting the status to passed when the title matches the regex might help? [@github/core](https://github.com/actions/toolkit/blob/master/packages/core/src/core.ts) doesn't seem to provide a method to do this though.

What are your thoughts?

![image](https://user-images.githubusercontent.com/2980428/78269051-f8a16d00-7500-11ea-9cac-120a40abf464.png)

**Comment by MorrisonCole** [comment]
Hey @krishna-acondy,

I'll take a look into this and get back to you - thanks for raising it! 🥇

**Comment by MorrisonCole** [comment]
Finally found what was happening here, and it seems to be a common issue actually ([see this thread](https://github.community/t5/GitHub-Actions/duplicate-checks-on-pull-request-event/td-p/33157)). Seems like GitHub doesn't combine the events because they are from different triggers.

The best workaround for now I think is to have the bot 'request changes' for non-matching PR titles. Ideally, both options would be viable but using the status check API has its downsides at the moment.

For now I'll make this change and release a new version!

**Comment by MorrisonCole** [comment]
@krishna-acondy released https://github.com/MorrisonCole/pr-lint-action/releases/tag/v1.1.0 which solves this issue 🎉 

Let me know if you're happy with the solution - if so, I'll close this 😃

**Comment by krishna-acondy** [comment]
Great job @MorrisonCole! 🥇 

This solution works for the moment. We can maybe revisit if anything changes in the way Github handles this. Happy to close this issue. 😄
